# coding: utf-8

"""
    Splunk Cloud Admin API

    API for managing splunk cloud stacks. (c) 2020 Splunk Inc. All rights reserved. I acknowledge that Splunk is not responsible for the installation or use of any application that is not a supported Splunk application and Splunk specifically disclaims the accuracy, integrity, quality, legality, usefulness or security of such application or its use. Installation and use of an application that is not a supported Splunk application is at your own risk. Please note that if data leaves Splunk Cloud as a result of installing or using such application, Splunk’s security attestations do not apply to data outside Splunk Cloud. Learn more about installing private apps (link to https://docs.splunk.com/Documentation/SplunkCloud/8.2.2109/Config/ManageApps). Access and use is subject to the Splunk General Terms (https://www.splunk.com/en_us/legal/splunk-general-terms.html) and Splunk's Website Terms and Conditions (https://www.splunk.com/en_us/legal/terms/terms-of-use.html).

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.maintenance_windows_change_freeze_response import MaintenanceWindowsChangeFreezeResponse

class TestMaintenanceWindowsChangeFreezeResponse(unittest.TestCase):
    """MaintenanceWindowsChangeFreezeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MaintenanceWindowsChangeFreezeResponse:
        """Test MaintenanceWindowsChangeFreezeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MaintenanceWindowsChangeFreezeResponse`
        """
        model = MaintenanceWindowsChangeFreezeResponse()
        if include_optional:
            return MaintenanceWindowsChangeFreezeResponse(
                customer_initiated_freezes = [
                    openapi_client.models.maintenance_windows_customer_initiated_freeze_response.MaintenanceWindowsCustomerInitiatedFreezeResponse(
                        applies_to = 'Splunk Initiated Changes Only', 
                        created_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        end_date = '2006/02/01', 
                        id = '', 
                        last_modified_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        reason = 'Black Friday/Cyber Monday Sales Week', 
                        start_date = '2006/02/01', 
                        tickets = ["SFDC-1234","SFDC-1235"], )
                    ],
                splunk_initiated_freezes = [
                    openapi_client.models.maintenance_windows_splunk_initiated_freeze_response.MaintenanceWindowsSplunkInitiatedFreezeResponse(
                        applies_to = 'Splunk Initiated Changes Only', 
                        category = 'Professional Services', 
                        created_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        end_date = '2006/02/01', 
                        id = '', 
                        last_modified_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        reason = 'Splunk Holiday', 
                        start_date = '2006/02/01', 
                        tickets = ["JIRA-1234","JIRA-1235"], )
                    ]
            )
        else:
            return MaintenanceWindowsChangeFreezeResponse(
                customer_initiated_freezes = [
                    openapi_client.models.maintenance_windows_customer_initiated_freeze_response.MaintenanceWindowsCustomerInitiatedFreezeResponse(
                        applies_to = 'Splunk Initiated Changes Only', 
                        created_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        end_date = '2006/02/01', 
                        id = '', 
                        last_modified_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        reason = 'Black Friday/Cyber Monday Sales Week', 
                        start_date = '2006/02/01', 
                        tickets = ["SFDC-1234","SFDC-1235"], )
                    ],
                splunk_initiated_freezes = [
                    openapi_client.models.maintenance_windows_splunk_initiated_freeze_response.MaintenanceWindowsSplunkInitiatedFreezeResponse(
                        applies_to = 'Splunk Initiated Changes Only', 
                        category = 'Professional Services', 
                        created_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        end_date = '2006/02/01', 
                        id = '', 
                        last_modified_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        reason = 'Splunk Holiday', 
                        start_date = '2006/02/01', 
                        tickets = ["JIRA-1234","JIRA-1235"], )
                    ],
        )
        """

    def testMaintenanceWindowsChangeFreezeResponse(self):
        """Test MaintenanceWindowsChangeFreezeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
