# coding: utf-8

"""
    Splunk Cloud Admin API

    API for managing splunk cloud stacks. (c) 2020 Splunk Inc. All rights reserved. I acknowledge that Splunk is not responsible for the installation or use of any application that is not a supported Splunk application and Splunk specifically disclaims the accuracy, integrity, quality, legality, usefulness or security of such application or its use. Installation and use of an application that is not a supported Splunk application is at your own risk. Please note that if data leaves Splunk Cloud as a result of installing or using such application, Splunk’s security attestations do not apply to data outside Splunk Cloud. Learn more about installing private apps (link to https://docs.splunk.com/Documentation/SplunkCloud/8.2.2109/Config/ManageApps). Access and use is subject to the Splunk General Terms (https://www.splunk.com/en_us/legal/splunk-general-terms.html) and Splunk's Website Terms and Conditions (https://www.splunk.com/en_us/legal/terms/terms-of-use.html).

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_hecs200_response import ListHECs200Response

class TestListHECs200Response(unittest.TestCase):
    """ListHECs200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListHECs200Response:
        """Test ListHECs200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListHECs200Response`
        """
        model = ListHECs200Response()
        if include_optional:
            return ListHECs200Response(
                http_event_collectors = [
                    openapi_client.models.hec_info.HecInfo(
                        spec = openapi_client.models.hec_spec.HecSpec(
                            allowed_indexes = [
                                ''
                                ], 
                            default_host = '', 
                            default_index = '', 
                            default_source = '', 
                            default_sourcetype = '', 
                            disabled = True, 
                            name = '', 
                            token = '', 
                            use_ack = True, ), 
                        token = '', )
                    ]
            )
        else:
            return ListHECs200Response(
        )
        """

    def testListHECs200Response(self):
        """Test ListHECs200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
